name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    rund-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/Krypton"
      - run: npm ci
      - run: npm test
