name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    rund-on: Ubuntu-latest
    steps:
      - uses: actions:checkout@v4

      - uses: actions:setup-node@v4
        with:
          node-verson: "20.12.1"

      - run: npm ci

      - run: npm test
